name: magnitude-bandit-analysis
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.17=h4ee41c1_0
  - pip=25.2=pyhc872135_0
  - python=3.13.7=hc28b8d9_100_cp313
  - python_abi=3.13=1_cp313
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py313hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - executing==2.2.1
      - fonttools==4.59.2
      - ipykernel==6.30.1
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - networkz==1.0.6
      - numpy==2.3.3
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pathlib==1.0.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - tzdata==2025.2
      - wcwidth==0.2.13
prefix: /Users/megyoung/anaconda3/envs/magnitude-bandit-analysis
